# SOUL.md — Universal AI Configuration for VAPTSecure Plugin

> **⚠️ CRITICAL DOCUMENT**
> This file loads from .ai/SOUL.md — the single source of truth.
>
> **DO NOT EDIT THIS FILE DIRECTLY.**
> Edit .ai/SOUL.md instead.

---

See .ai/SOUL.md for full documentation.

